dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - flake8
  - pytest --cov

after_success:
  - pip install codecov
  - codecov -t f55d4c4d-a471-4815-96e3-3b140f8a99e2
